### ISSUE TITLE
jq: error (at <stdin>:0): Cannot iterate over null (null)

### ISSUE THREAD

**Issue by ong-andrew** [lvxchild/OpenWeather#1]
Hi there. The output I got is this. Not sure what's up.

```
cat: /Banner.txt: No such file or directory
jq: error (at <stdin>:0): Cannot iterate over null (null)
The temperature is C, but it feels like C
The humidity is at %@’
Min: C | Max: Cse at  and set at 
date: invalid date ‘@’
date: invalid date ‘@’
The sun will rise at  and set at 
```

Thank you

**Comment by lvxchild** [comment]
Thanks for the feedback. I found the error was a '-e' flag in the Install.sh and UpdatePrefs.sh files which prevented the API key from being loaded in the URL query properly. I updated the correct files so it should be working fine now.
